name: CI - Visual Studio 2017

on:
  push:
    tags-ignore: 
      - '*'

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v1
    - name: Build Compression Libraries...
      shell: cmd
      run: .\win\ymlBuild.bat
     
    - uses: actions/upload-artifact@v1
      if: success()
      with:
        name: SQUASHFS-WinInstaller
        path: .\win\installer\x64\ReleaseMT\squashfs_win.msi
