name: CI - Visual Studio 2017

on: [push]

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v1
    - name: Build Compression Libraries...
      run: |
        dir "c:\Program Files (x86)\Microsoft Visual Studio\"
    - name: Build SquashFS installer
      run: |
        dir "c:\Program Files (x86)\Microsoft Visual Studio\2017"
