name: CI - Visual Studio 2017

on: [push]

jobs:
  build:

    runs-on: windows-2016

    steps:
#    - uses: actions/checkout@v1
    - name: Build Compression Libraries...
      run: robocopy c:\ c:\ /L /S /NJH /NJS /NS /LEV:5 > .\dir.log
     
    - uses: actions/upload-artifact@v1
      if: success()
      with:
        name: SQUASHFS-WinInstaller
        path: .\dir.log
#        path: .\win\installer\x64\ReleaseMT\squashfs_win.msi
