name: CI - Visual Studio 2017

on:
  push:
    tags:
    - '!v*'

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v1
    - name: Build SQUASHFS-Win...
      shell: cmd
      run: .\.github\workflows\ymlBuild.bat
     
    - uses: actions/upload-artifact@v1
      if: success()
      with:
        name: SQUASHFS-WinInstaller
        path: .\win\installer\x64\ReleaseMT\squashfs_win.msi
